### PR TITLE
Discrete_potential

### PR DESCRIPTION
**Pull request by vkrajnak**
As demonstrated in the notebook, `fit_surface` returns a fitted surface and it works well. It is not the prettiest implementation, so every suggestion is welcome.

### CODE REVIEW

**Comment by broncio123** [comment]
Hey, @vkrajnak  I have a few suggestions for the Examples NB:

* Move lines to generate discrete Henon-Heiles PES to a script living under some folder, for example `testing_scripts` within `pylds`
* Decide on a format to store PES data - perhaps CSV, and save in a folder that can be dedicated to saving sample PES data, for example, `HenonHeiles_pes_data.csv`.
* Then, add code lines to load PES data from a file to be passed to `fit_surface`.

I make these suggestions in the spirit that the Examples NB must be exclusive to show users how to use the various methods on the package, it shouldn't contain testing lines.

Also, some alternative variable names for readability
* `pot` -> `pes_data`
* `fit_surface` -> `fit_pes`

I still need to test for boundary effects on the output of the spline functions if taking a value far away from the domain. 
I'll do that in another comment later on.

**Comment by broncio123** [comment]
> As demonstrated in the notebook, `fit_surface` returns a fitted surface and it works well. It is not the prettiest implementation, so every suggestion is welcome.

See comments, please :)

**Comment by vkrajnak** [comment]
Done. Any more suggestions?

**Comment by broncio123** [comment]
> Done. Any more suggestions?

Hi @vkrajnak everything fine. I just made a few minor modifications. 
Please go ahead with the pull-request.

**Comment by vkrajnak** [comment]
@broncio123 I'll need your help here

**Review by broncio123 — COMMENTED** [review]
I'm happy with all the changes. Please, feel free to proceed with the pull-request.

**Comment by broncio123** [comment]
> @broncio123 I'll need your help here

Sure, I can help with this one.

**Comment by vkrajnak** [comment]
Thank you very much!

**Pull request merged**
